Add celery configuration
knmlprz/ChatKNML pull request #128
Opened 2024-04-11 12:47 UTC by Sygnator

close https://github.com/knmlprz/ChatKNML/issues/125

2024-04-11 13:57 UTC, pgronkievitz requested changes

2024-04-11 13:57 UTC, pgronkievitz commented on api/Dockerfile
> +CMD celery -A czatknml.celery worker -l info
Lack of newline at EOF

2024-04-16 07:03 UTC, pgronkievitz approved these changes

2024-04-16 07:58 UTC, sand194 approved these changes

2024-04-16 08:56 UTC, merged