Documents with chunks
knmlprz/ChatKNML pull request #129
Opened 2024-04-11 23:50 UTC by annbbbb

### Changes

- new function `split_documents_into_chunks` for generating document chunks in the `./api/chunks/utils.py`;
- modified `create_document_controller` and `update_document_controller` to create chunks on document creation and update.

2024-04-12 09:27 UTC, pgronkievitz requested changes

2024-04-12 09:27 UTC, pgronkievitz commented on api/chunks/utils.py
> +    return chunks
**suggestion:** there's a lot of places where you can achieve off-by-one errors this way, we can use more automatic way (this code seems to work fine in the REPL, but make sure it's formatted etc., as I wrote it in the suggestion box xD)

I don't really like solution with `next_start_char`, but I don't have any better idea right now (as we have to check chunk's length anyway for this)
```suggestion
from documents.models import Document
from itertools import batched


def split_document_into_chunks(document: Document, chunk_size: int = 100) -> list[dict]:
    """Splits document into chunks of size chunk_size and returns them as dictionaries.
    End_char is assumed to be the last included character of the document."""
    
    chunks = []
    start_char = 0
    
    for i, chunk in enumerate(batched(document.text, chunk_size)):
        next_start_char = start_char + len(chunk)
        
        chunks.append({
            "text": "".join(chunk),
            "chunk_idx": i,
            "start_char": start_char,
            "end_char": next_start_char - 1,
            "document_idx": document.id,
        })
        
        start_char = next_start_char
    
    return chunks
```

2024-05-21 19:46 UTC, TheJimmyNowak requested changes

2024-05-21 19:46 UTC, TheJimmyNowak commented on api/documents/controllers.py
> +        # Removed individual chunk save operations for efficiency
Unnecessary comments

2024-05-21 20:09 UTC, TheJimmyNowak approved these changes

2024-05-22 08:06 UTC, pgronkievitz requested changes

2024-05-22 14:43 UTC, pgronkievitz approved these changes

2024-05-22 14:46 UTC, merged