Saving conversations in txt files
knmlprz/ChatKNML pull request #43
Opened 2023-11-29 22:46 UTC by TheJimmyNowak

2023-11-29 23:11 UTC, TheJimmyNowak reviewed
Fajny początek! Tak jak już mówiłem na spotkaniu zapisywanie historii do .txt jest takie se. Zerknij [tutaj](https://discordpy.readthedocs.io/en/latest/api.html#discord.TextChannel.history) i [tutaj](https://stackoverflow.com/questions/63863871/discord-py-how-to-go-through-channel-history-and-search-for-a-specific-message) i zobacz czy działa to dla DM'ów i czy api discorda nakłada na to jakieś ograniczenia (tak jak @Sygnator mówił).

Dorzucając jeszcze radę. Rób częściej commity i opisuj je ładnie to jest bardzo dobra praktyka, bo inni widzą jak ten kod zmieniałeś i jakie rzeczy uwzględniałeś przy tworzeniu kodu.

2023-11-29 23:11 UTC, TheJimmyNowak commented on discord/bot.py
> +bot.run("MTE3NTUwNDAwMTc4NjE4NzgxNg.GeJlgw.at5Pn28P4hiYlKssHgzNyz2l80oQIwOjIeMG_k")
Nigdy nie wrzucamy tokenów i secretów na repo w szczególności publiczne 😉 
Bota odpalamy z `docker-compoe.yml `, a w głównym folderze robimy plik `.env` i tam wrzucamy token. Obrazek się buduje z twoim tokenem w środku, a plik `.env` jest w `.gitignore`, więc nie pójdzie na remot'a

P.S. Dla innych reviewerów gadałem już na ten temat z szymonem i discord zresetował mu token więc nic się nie stało

2023-11-29 23:11 UTC, TheJimmyNowak commented on discord/bot.py
> +# wywołanie bota i przejście do rozmowy prywatnej
Jak piszemy kod po angielsku, to komentarze też po angielsku 😝  btw. komentarz raczej tutaj jest nie potrzebny. Bo nazwa funkcji mówi sama za siebie. 

Zmien komendę na małe litery imo. I tak nazwy komend będziemy wymyślać jeszcze. 
[StackOverflow Best practieces for writing good comments] (https://stackoverflow.blog/2021/12/23/best-practices-for-writing-code-comments/)

2023-11-30 19:13 UTC, pgronkievitz requested changes

2023-11-30 19:13 UTC, pgronkievitz commented on discord/bot.py
> +        filename = f"discord/private_chats/{interaction.user.id}.txt"
This implementation is OS-specific
See: https://docs.python.org/3/library/pathlib.html

2023-11-30 19:13 UTC, pgronkievitz commented on discord/bot.py
> +bot.run("MTE3NTUwNDAwMTc4NjE4NzgxNg.GeJlgw.at5Pn28P4hiYlKssHgzNyz2l80oQIwOjIeMG_k")
> Nigdy nie wrzucamy tokenów i secretów na repo w szczególności publiczne 😉 Bota odpalamy z `docker-compoe.yml `, a w głównym folderze robimy plik `.env` i tam wrzucamy token. Obrazek się buduje z twoim tokenem w środku, a plik `.env` jest w `.gitignore`, więc nie pójdzie na remot'a
> 
> P.S. Dla innych reviewerów gadałem już na ten temat z szymonem i discord zresetował mu token więc nic się nie stało

Prawie - tokena w takiej sytuacji nie ma wewnątrz obrazka

2023-12-05 21:24 UTC, TheJimmyNowak commented on discord/.gitignore
> +private_chats/*.txt
Delete these changes

2023-12-05 21:24 UTC, TheJimmyNowak commented on discord/bot.py
> +async def start_bot(bot):
We have another way to start our bot on main branch! You will need to resolve your conflicts when marging

2023-12-05 21:24 UTC, TheJimmyNowak commented on discord/bot.py
> +async def chats_history(bot, last_messages_per_channel):
Make this function to return a dict

2023-12-05 21:44 UTC, TheJimmyNowak commented on discord/bot.py
> +async def get_chats_history(bot):
You do not need an argument here :wink:

2023-12-05 21:44 UTC, TheJimmyNowak commented on discord/bot.py
> +                    chats_history[channel.id].append(f"{message.author.name}: {message.content}")
You can use lambda expressions (map, filter, reduce etc) to make it cleaner

2023-12-05 21:45 UTC, TheJimmyNowak commented on discord/bot.py
> +                    chats_history[channel.id].append(f"{message.author.name}: {message.content}")
https://realpython.com/python-map-function/

2023-12-11 21:27 UTC, pgronkievitz requested changes

2023-12-12 16:56 UTC, finloop requested changes
**issue (blocking):** Update your branch, then rerequest review.

2023-12-12 16:56 UTC, finloop commented on discord/.gitignore
> -
**suggestion (non-blocking):** Add newline to the end of file

```suggestion
.idea/

```

2023-12-13 20:23 UTC, pgronkievitz approved these changes
There's no return type in `get_chats_history`, but ok

2023-12-13 20:23 UTC, merged