Create CONTRIBUTING.md
knmlprz/ChatKNML pull request #72
Opened 2023-12-07 19:00 UTC by KacperD1756

Closes #25

2023-12-08 11:17 UTC, finloop commented on CONTRIBUTING.md
> +
Za dużo enterów. Zainstaluj sobie git hooki (Ania wrzuciła instrukcje), one Ci przeformatują ten plik.

2023-12-08 11:18 UTC, finloop commented on CONTRIBUTING.md
> +3. Zrób pull requesta - Wejdź w swoje repozytorium, oraz wybierz opcję "Pull Requests", następnie kliknij w zielony przycisk "New pull request" i po upewnieniu się, że Twoje repozytorium będzie porów
Usunąłem artefakt po forkach.

```suggestion
3. Zrób pull requesta - Wejdź w swoje repozytorium, oraz wybierz opcję "Pull Requests", następnie kliknij w zielony przycisk "New pull request". Wpisz tytuł oraz opis pull requesta i jako Reviewers wybierz osobę, która zleciła Ci wykonanie projektu. Jeżeli Twój kod zostanie uznany za dobry otrzymasz zgodę na jego zmergowanie. 
```

2023-12-08 11:19 UTC, finloop requested changes
Przeformatuj ten plik, poza tym jest super :+1: +1

2024-01-08 18:08 UTC, TheJimmyNowak approved these changes

2024-01-08 18:09 UTC, merged