naprawione readme
knmlprz/ChatKNML pull request #74
Opened 2023-12-11 17:21 UTC by Karolingo

2023-12-11 17:36 UTC, TheJimmyNowak requested changes

2023-12-11 17:36 UTC, TheJimmyNowak commented on discord_bot/README.md
> +direct link - **https://github.com/knmlprz/ChatKNML.git**
Użyj git clone

2023-12-11 17:36 UTC, TheJimmyNowak commented on discord_bot/README.md
> +### After docker has been installed, make sure to register and log in to docker desktop.
Use warning quote from github markdown docs

2023-12-11 17:36 UTC, TheJimmyNowak commented on discord_bot/README.md
>  ```bash
Delete this

2023-12-11 17:36 UTC, TheJimmyNowak commented on discord_bot/README.md
>  ## Setup
Use headear 1

2023-12-11 17:36 UTC, TheJimmyNowak commented on discord_bot/README.md
> +pip poetry install
Do not install poetry using pip. 
```sh
pip install pipx
pipx install poetry
```

2023-12-11 17:36 UTC, TheJimmyNowak commented on docker-compose.yml
> +
Use `git reset --soft ~` and fix this

2023-12-11 17:36 UTC, TheJimmyNowak commented on discord_bot/README.md
> +from "/discord_bot/discord_bot" path run bot.py
Improve this pls

2023-12-14 21:05 UTC, TheJimmyNowak approved these changes
lgtm

2023-12-15 07:16 UTC, finloop approved these changes
LGTM

2023-12-15 07:16 UTC, merged