Dockerfile for llm and service in docker compose
knmlprz/ChatKNML pull request #98
Opened 2024-02-22 00:32 UTC by Kleczyk

To run llm you need to download the model from hugingface:
```sh
wget -P ./llm/models https://huggingface.co/TheBloke/Llama-2-7B-GGUF/resolve/main/llama-2-7b.Q3_K_L.gguf
```
smaller model does not work 
### Endpoint to send prompt 
POST 127.0.0.1:9000/v1/completions
Request body

```json
{
  "prompt": "\n\n### Instructions:\nWhat is the capital of France?\n\n### Response:\n",
  "stop": [
    "\n",
    "###"
  ]
}
```
### Successful Response

```json
{
  "id": "string",
  "object": "text_completion",
  "created": 0,
  "model": "string",
  "choices": [
    {
      "text": "string",
      "index": 0,
      "logprobs": {
        "text_offset": [
          0
        ],
        "token_logprobs": [
          0,
          null
        ],
        "tokens": [
          "string"
        ],
        "top_logprobs": [
          {
            "additionalProp1": 0,
            "additionalProp2": 0,
            "additionalProp3": 0
          },
          null
        ]
      },
      "finish_reason": "stop"
    }
  ],
  "usage": {
    "prompt_tokens": 0,
    "completion_tokens": 0,
    "total_tokens": 0
  }
}
```

### Validation Error
```json
{
  "detail": [
    {
      "loc": [
        "string",
        0
      ],
      "msg": "string",
      "type": "string"
    }
  ]
}
```

2024-02-24 08:04 UTC, pgronkievitz requested changes

2024-02-24 08:04 UTC, pgronkievitz commented on llm/test/test_llm.py
> +    assert 'text' in response.json()['choices'][0]
**suggestion:** removed redundant test and simplified code (it should be a little faster)
```suggestion
	resp_body = response.json()
    assert 'choices' in resp_body
    assert 'text' in resp_body['choices'][0]
```

2024-02-24 08:04 UTC, pgronkievitz commented on llm/test/test_promt.py
**praise:** this doesn't seem to be proper pytest test and it seems like kinda duplicate of test_llm file

2024-02-24 08:04 UTC, pgronkievitz commented on llm/test/test_llm.py
> +def test_llm_response():
**praise:** add [mark it requires running LLM](https://docs.pytest.org/en/latest/how-to/mark.html), custom LLM mark or something like that

2024-02-24 10:48 UTC, Kleczyk commented on llm/test/test_promt.py
this is a quick check of what llm is responding to us sometimes it can be useful

2024-02-25 10:08 UTC, pgronkievitz commented on llm/test/test_promt.py
does it have any advantage over running regular test doing exactly the same?

2024-02-25 10:10 UTC, pgronkievitz approved these changes
in general lgtm

2024-02-25 10:10 UTC, pgronkievitz commented on README.md
>  ```
**suggestion (non-blocking):** please add both instructions with curl and wget

2024-02-25 10:44 UTC, merged